name: articles_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.27.3
  retrofit: ^3.0.1+1
  drift: ^1.5.0
  flutter_bloc: ^8.0.1
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.0
  dio: ^4.0.4
  cached_network_image: ^3.2.0
  json_annotation: ^4.4.0


dev_dependencies:
  drift_dev: ^1.5.2
  build_runner: ^2.1.8
  json_serializable: ^6.1.5
  retrofit_generator: ^4.0.1

  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
